version: 2
jobs:
  build:
    working_directory: /go/src/github.com/webnice/migrate/gsmigrate
    docker:
      - image: circleci/golang:1.8

    steps:
      - checkout

      - run: make dep
      - run: make test
